version: '3'

services:
  db:
    container_name: refine_db
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: root
    ports:
      - 3306:3306

  web:
    container_name: refine_web
    build:
      context: .
      dockerfile: docker/web/Dockerfile
    command: /bin/sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app
    ports:
      - 3000:3000
    links:
      - db
      - elasticsearch
    depends_on:
      - fluentd
    environment:
      FLUENTD_URL: http://fluentd:42442/fluent?messages_type=string&severity_key=level

  elasticsearch:
    container_name: refine_elasticsearch
    build:
      context: .
      dockerfile: docker/elasticsearch/Dockerfile
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - es_data:/usr/share/elasticsearch/data

  kibana:
    container_name: refine_kibana
    build:
      context: .
      dockerfile: docker/kibana/Dockerfile
    ports:
      - 5601:5601
    links:
      - elasticsearch
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200

  fluentd:
    container_name: refine_fluentd
    build:
      context: .
      dockerfile: docker/fluentd/Dockerfile
    ports:
      - 24224:24224
    environment:
      FLUENTD_CONF: fluent.conf
    depends_on:
      - mongodb

  mongodb:
    container_name: refine_mongodb
    restart: always
    build:
      context: .
      dockerfile: docker/mongodb/Dockerfile
    ports:
      - 27017:27017
    volumes:
      - log_data:/data/db
      - log_data:/data/configdb

  mongo_express:
    container_name: refine_mongodb_express
    build:
      context: .
      dockerfile: docker/mongo_express/Dockerfile
    restart: always
    ports:
      - 8081:8081
    depends_on:
      - mongodb

volumes:
  es_data:
    driver: local
  log_data:
    driver: local
