version: '3.4'

x-logging:
  &default-logging
  driver: fluentd
  options:
    fluentd-address: localhost:24224
    tag: "log.{{.Name}}"

services:
  db:
    container_name: refine_db
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: root
    ports:
      - 3306:3306

  web:
    container_name: refine_web
    build:
      context: .
      dockerfile: docker/web/Dockerfile
    command: /bin/sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app
    ports:
      - 3000:3000
    links:
      - db
      - fluentd
      - elasticsearch
    environment:
      FLUENTD_URL: http://fluentd:42442/fluent?messages_type=string&severity_key=level

  elasticsearch:
    container_name: refine_elasticsearch
    build:
      context: .
      dockerfile: docker/elasticsearch/Dockerfile
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - es_data:/usr/share/elasticsearch/data
    logging: *default-logging

  kibana:
    container_name: refine_kibana
    build:
      context: .
      dockerfile: docker/kibana/Dockerfile
    ports:
      - 5601:5601
    links:
      - elasticsearch
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
    logging: *default-logging

  fluentd:
    container_name: refine_fluentd
    build:
      context: .
      dockerfile: docker/fluentd/Dockerfile
    ports:
      - 24224:24224
    links:
      - mongodb

  mongodb:
    container_name: refine_mongodb
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 27017:27017
    volumes:
      - log_data:/data/db
      - log_data:/data/configdb

  mongo_express:
    container_name: refine_mongodb_express
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: refine_mongodb
      ME_CONFIG_BASICAUTH_USERNAME: root
      ME_CONFIG_BASICAUTH_PASSWORD: password
    links:
      - mongodb

volumes:
  es_data:
    driver: local
  log_data:
    driver: local
