# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2
jobs:
 build:
   machine: true
   environment:
     DB_HOST_NAME: localhost:3306
     DB_USER_NAME: root
     DB_PASSWORD: password
   steps:
    - checkout
    - run:
        name: build docker
        command: |
          docker-compose up -d --build

    - run: docker exec -it repo_web_1 bundle exec rake db:create
    - run: docker exec -it repo_web_1 bundle exec rake db:schema:load

    - run:
        name: run tests
        command: |
          TEST_FILES="$(circleci tests glob "spec/**/*_spec.rb" | \
            circleci tests split --split-by=timings)"

          docker exec -it repo_web_1 bundle exec rspec \
            --format progress \
            --format RspecJunitFormatter \
            --out /tmp/test-results/rspec.xml \
            --format progress \
            $TEST_FILES
