# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2.1
executors:
  default:
    working_directory: ~/workspace
    docker:
      - image: circleci/ruby:2.6.3-node-browsers
      - image: circleci/mysql:5.7
commands:
  restore_gem:
    steps:
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "Gemfile.lock" }}
          - v1-dependencies-

  save_gem:
    steps:
      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}
jobs:
  test:
    executor:
      name: default
    environment:
      RAILS_ENV: test
      DB_HOST_NAME: 127.0.0.1
      DB_USER_NAME: 'root'
      DB_PASSWORD: ''
    working_directory: ~/repo
    steps:
      - checkout
      - restore_gem
      - run:
          name: install dependencies
          command: |
            bundle install --jobs=4 --retry=3 --path vendor/bundle
      - save_gem
      - run:
          name: Wait for DB
          command: dockerize -wait tcp://127.0.0.1:3306 -timeout 120s
      - run: bundle exec rake db:create
      - run: bundle exec rake db:schema:load
      - run:
          name: run tests
          command: |
            mkdir /tmp/test-results
            TEST_FILES="$(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)"

            bundle exec rspec --format RspecJunitFormatter \
                              --out /tmp/test-results/rspec.xml \
                              --format progress \
                              $TEST_FILES
      - store_test_results:
          path: /tmp/test-results
      - store_artifacts:
          path: /tmp/test-results
          destination: test-results

  code_analysis:
    executor:
      name: default
    working_directory: ~/repo
    steps:
      - checkout
      - restore_gem
      - run:
          name: install dependencies
          command: |
            bundle install --jobs=4 --retry=3 --path vendor/bundle
      - run:
          name: rubocop
          command: bundle exec rubocop

  brakeman:
    executor:
      name: default
    working_directory: ~/repo
    steps:
      - checkout
      - restore_gem
      - run:
          name: install dependencies
          command: |
            bundle install --jobs=4 --retry=3 --path vendor/bundle
      - run:
          name: brakeman
          command: bundle exec brakeman

workflows:
  version: 2
  test:
    jobs:
      - test
  code_analysis:
    jobs:
      - code_analysis
  security:
    jobs:
      - brakeman
