FROM kibana:7.2.0

ENV xpack.graph.enabled false
ENV xpack.ml.enabled false
ENV xpack.monitoring.enabled false
ENV xpack.reporting.enabled false
ENV xpack.security.enabled false
ENV xpack.monitoring.report_stats false
ENV xpack.monitoring.ui.enabled false
