production:
  github:
    key: xxxxxxxxxxx
    secret: XXXXXXXXXXXXXXXXXXXXXXXXX
  google:
    key: xxxxxxxxxxx
    secret: XXXXXXXXXXXXXXXXXXXXXXXXX

development: &development
  github:
    key: fa8701a8d401c2f496d4
    secret: 0399c57beb546bafb61adce4710ff3924260bf4f
  google:
    key: 735882136120-oc8rss2ns06l83jsf2blnrhv5rv4md00.apps.googleusercontent.com
    secret: CMobfewTa-kVutgk9HBY0c12

test:
  <<: *development
