FROM elasticsearch:7.2.0

ENV discovery.type single-node
ENV ES_JAVA_OPTS "-Xms512m -Xmx512m"
ENV xpack.graph.enabled false
ENV xpack.ml.enabled false
ENV xpack.monitoring.enabled false
ENV xpack.security.enabled false
ENV xpack.watcher.enabled false
